TUNING.KYNO_FISH_LARGE_HEALTH = 4
TUNING.KYNO_FISH_LARGE_HUNGER = 25
TUNING.KYNO_FISH_LARGE_SANITY = 0

TUNING.KYNO_FISH_LARGE_COOKED_HEALTH = 8
TUNING.KYNO_FISH_LARGE_COOKED_HUNGER = 25
TUNING.KYNO_FISH_LARGE_COOKED_SANITY = 5

TUNING.KYNO_FISH_SMALL_HEALTH = 1
TUNING.KYNO_FISH_SMALL_HUNGER = 12.5
TUNING.KYNO_FISH_SMALL_SANITY = 0

TUNING.KYNO_FISH_SMALL_COOKED_HEALTH = 3
TUNING.KYNO_FISH_SMALL_COOKED_HUNGER = 12.5
TUNING.KYNO_FISH_SMALL_COOKED_SANITY = 1