-- SOTS_Mode_Modifier
-- Author: Ithildin
-- DateCreated: 2/4/2023 8:49:11 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO Leaders_XP2 (LeaderType, OceanStart)
SELECT	LeaderType,	1		FROM Leaders WHERE InheritFrom = 'LEADER_DEFAULT';

CREATE TRIGGER SOTS_OCEAN_START	AFTER INSERT ON Leaders WHEN NEW.InheritFrom = 'LEADER_DEFAULT'
BEGIN
	INSERT OR REPLACE INTO Leaders_XP2 (LeaderType, OceanStart)
	VALUES	(NEW.LeaderType, 1);
END;

INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES	('TRAIT_SOTS_TERRAIN_CHANGER',					'MODFEAT_SOTS_EARLY_EMBARK_OCEAN'),
		('TRAIT_SOTS_TERRAIN_CHANGER',					'TRAIT_MAORI_EMBARKED_ABILITY'),
		('TRAIT_SOTS_TERRAIN_CHANGER',					'SCIENCE_PRESETTLEMENT'),
		('TRAIT_SOTS_TERRAIN_CHANGER',					'CULTURE_PRESETTLEMENT'),
		('TRAIT_SOTS_TERRAIN_CHANGER',					'BUILDER_PRESETTLEMENT'),
		('TRAIT_SOTS_TERRAIN_CHANGER',					'POPULATION_PRESETTLEMENT'),
		('TRAIT_SOTS_TERRAIN_CHANGER',					'TRAIT_MAORI_MANA_SAILING');

INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_SOTS_TERRAIN_CHANGER',					'MODFEAT_SOTS_EARLY_EMBARK_'||UnitType	FROM Units;

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
SELECT	'MODFEAT_SOTS_EARLY_EMBARK_'||UnitType,			'MODIFIER_SOTS_ADJUST_EMBARK_UNIT_PASS' FROM Units;

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'MODFEAT_SOTS_EARLY_EMBARK_'||UnitType,			'UnitType',			UnitType 			FROM Units;

CREATE TRIGGER SOTS_EARLY_EMBARK	AFTER INSERT ON Units WHEN NEW.UnitType NOT NULL
BEGIN
	INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
	VALUES	('TRAIT_SOTS_TERRAIN_CHANGER',					'MODFEAT_SOTS_EARLY_EMBARK_'||NEW.UnitType);

	INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
	VALUES	('MODFEAT_SOTS_EARLY_EMBARK_'||NEW.UnitType,	'MODIFIER_SOTS_ADJUST_EMBARK_UNIT_PASS');

	INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
	VALUES	('MODFEAT_SOTS_EARLY_EMBARK_'||NEW.UnitType,	'UnitType',	NEW.UnitType);
END;

--э竟
INSERT OR REPLACE INTO Types (Type, Kind)
VALUES	('MODIFIER_SOTS_ADJUST_EMBARK_UNIT_PASS',	'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
VALUES	('MODIFIER_SOTS_ADJUST_EMBARK_UNIT_PASS',	'COLLECTION_OWNER',	'EFFECT_ADJUST_PLAYER_EMBARK_UNIT_PASS');
