-- Kurumi_Requirement
-- Author: Ithildin
-- DateCreated: 8/19/2021 11:22:45 AM
--------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES	('REQSET_SOTS_OCEAN_CITY',		'REQUIREMENTSET_TEST_ANY'),
		('REQSET_SOTS_WATER_PLOT',		'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES	('REQSET_SOTS_OCEAN_CITY',		'REQ_SOTS_CITY_HAS_6_COAST'),
		('REQSET_SOTS_OCEAN_CITY',		'REQ_SOTS_CITY_HAS_3_OCEAN'),
		('REQSET_SOTS_WATER_PLOT',		'REQ_SOTS_WATER_PLOT');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
VALUES	('REQ_SOTS_CITY_HAS_6_COAST',	'REQUIREMENT_CITY_HAS_X_TERRAIN_TYPE'),
		('REQ_SOTS_CITY_HAS_3_OCEAN',	'REQUIREMENT_CITY_HAS_X_TERRAIN_TYPE'),
		('REQ_SOTS_WATER_PLOT',			'REQUIREMENT_PLOT_TERRAIN_CLASS_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
VALUES	('REQ_SOTS_CITY_HAS_6_COAST',	'TerrainType',	'TERRAIN_COAST'),
		('REQ_SOTS_CITY_HAS_6_COAST',	'Amount',		6),
		('REQ_SOTS_CITY_HAS_3_OCEAN',	'TerrainType',	'TERRAIN_OCEAN'),
		('REQ_SOTS_CITY_HAS_3_OCEAN',	'Amount',		3),
		('REQ_SOTS_WATER_PLOT',			'TerrainClass',	'TERRAIN_CLASS_WATER');

--WaterDist 2679992682
INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT			'REQSET_IS_'||DistrictType,					'REQUIREMENTSET_TEST_ALL'	FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQSET_IS_'||BuildingType,					'REQUIREMENTSET_TEST_ALL'	FROM Buildings WHERE BuildingType LIKE 'BUILDING_SOTS_COAST_%'
UNION SELECT	'REQSET_'||DistrictType||'_HIGH_ADJACENCY',	'REQUIREMENTSET_TEST_ALL'	FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%';

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT			'REQSET_IS_'||DistrictType,					'REQ_IS_'||DistrictType					FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQSET_IS_'||BuildingType,					'REQ_IS_'||BuildingType					FROM Buildings WHERE BuildingType LIKE 'BUILDING_SOTS_COAST_%'
UNION SELECT	'REQSET_'||DistrictType||'_HIGH_ADJACENCY',	'REQ_'||DistrictType||'_HIGH_ADJACENCY'	FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%';

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
SELECT			'REQ_IS_'||DistrictType,					'REQUIREMENT_DISTRICT_TYPE_MATCHES'					FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_PLOT_IS_'||DistrictType,				'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES'			FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_PLOT_ADJ_'||DistrictType,				'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES'	FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_IS_'||BuildingType,					'REQUIREMENT_CITY_HAS_BUILDING'						FROM Buildings WHERE BuildingType LIKE 'BUILDING_SOTS_COAST_%'
UNION SELECT	'REQ_'||DistrictType||'_HIGH_ADJACENCY',	'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'		FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%';

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
SELECT			'REQ_IS_'||DistrictType,					'DistrictType', DistrictType							FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_PLOT_IS_'||DistrictType,				'DistrictType',	DistrictType							FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_PLOT_ADJ_'||DistrictType,				'DistrictType',	DistrictType							FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_IS_'||BuildingType,					'BuildingType',		BuildingType						FROM Buildings WHERE BuildingType LIKE 'BUILDING_SOTS_COAST_%'
UNION SELECT	'REQ_'||DistrictType||'_HIGH_ADJACENCY',	'DistrictType', 'DISTRICT_SOTS_COAST_CAMPUS'			FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_'||DistrictType||'_HIGH_ADJACENCY',	'YieldType', 'YIELD_'||TRIM(PlunderType, 'PLUNDER_')	FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%'
UNION SELECT	'REQ_'||DistrictType||'_HIGH_ADJACENCY',	'Amount', 3												FROM Districts WHERE DistrictType LIKE 'DISTRICT_SOTS_COAST_%';

INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES	('REQSET_IS_BUILDING_SOTS_COAST_POWER_PLANTS',		'REQUIREMENTSET_TEST_ANY'),
		('REQSET_SOTS_HOLY_SITE_FOLLOWS_RELIGION',			'REQUIREMENTSET_TEST_ALL'),
		('REQSET_SOTS_HOLY_SITE_ADJACENT_RIVER',			'REQUIREMENTSET_TEST_ALL'),
		('REQSET_SOTS_ADJ_HOLY_SITE',						'REQUIREMENTSET_TEST_ALL'),
		('REQSET_SOTS_8INCLUDE_HOLY_SITE',					'REQUIREMENTSET_TEST_ALL'),

		('REQSET_SOTS_CITY_HAS_SHRINE',						'REQUIREMENTSET_TEST_ALL'),
		('REQSET_SOTS_CITY_FOLLOWS_RELIGION_HAS_SHRINE',	'REQUIREMENTSET_TEST_ALL'),
		('REQSET_SOTS_CITY_HAS_TEMPLE',						'REQUIREMENTSET_TEST_ALL'),
		('REQSET_SOTS_CITY_FOLLOWS_RELIGION_HAS_TEMPLE',	'REQUIREMENTSET_TEST_ALL');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES	('REQSET_IS_BUILDING_SOTS_COAST_POWER_PLANTS',		'REQ_IS_BUILDING_SOTS_COAST_COAL_PLANT'),
		('REQSET_IS_BUILDING_SOTS_COAST_POWER_PLANTS',		'REQ_IS_BUILDING_SOTS_COAST_FOSSIL_FUEL_PLANT'),
		('REQSET_IS_BUILDING_SOTS_COAST_POWER_PLANTS',		'REQ_IS_BUILDING_SOTS_COAST_NUCLEAR_PLANT'),
		('REQSET_SOTS_HOLY_SITE_FOLLOWS_RELIGION',			'REQUIRES_CITY_FOLLOWS_RELIGION'),
		('REQSET_SOTS_HOLY_SITE_FOLLOWS_RELIGION',			'REQ_PLOT_IS_DISTRICT_SOTS_COAST_HOLY_SITE'),
		('REQSET_SOTS_HOLY_SITE_ADJACENT_RIVER',			'REQUIRES_PLOT_ADJACENT_TO_RIVER'),
		('REQSET_SOTS_HOLY_SITE_ADJACENT_RIVER',			'REQ_PLOT_IS_DISTRICT_SOTS_COAST_HOLY_SITE'),
		('REQSET_SOTS_ADJ_HOLY_SITE',						'REQ_PLOT_ADJ_DISTRICT_SOTS_COAST_HOLY_SITE'),
		('REQSET_SOTS_8INCLUDE_HOLY_SITE',					'REQ_MUKURO_8INCLUDE_HOLY_SITE'),

		('REQSET_SOTS_CITY_HAS_SHRINE',						'REQ_IS_BUILDING_SOTS_COAST_SHRINE'),
		('REQSET_SOTS_CITY_FOLLOWS_RELIGION_HAS_SHRINE',	'REQUIRES_CITY_FOLLOWS_RELIGION'),
		('REQSET_SOTS_CITY_FOLLOWS_RELIGION_HAS_SHRINE',	'REQ_IS_BUILDING_SOTS_COAST_SHRINE'),
		('REQSET_SOTS_CITY_HAS_TEMPLE',						'REQ_IS_BUILDING_SOTS_COAST_TEMPLE'),
		('REQSET_SOTS_CITY_FOLLOWS_RELIGION_HAS_TEMPLE',	'REQUIRES_CITY_FOLLOWS_RELIGION'),
		('REQSET_SOTS_CITY_FOLLOWS_RELIGION_HAS_TEMPLE',	'REQ_IS_BUILDING_SOTS_COAST_TEMPLE'),

		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_CATHEDRAL'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_GURDWARA'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_MEETING_HOUSE'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_MOSQUE'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_PAGODA'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_SYNAGOGUE'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_WAT'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_STUPA'),
		('BUILDING_IS_TIER3_HOLY_SITE',					'REQ_IS_BUILDING_SOTS_COAST_DAR_E_MEHR');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
VALUES	('REQ_MUKURO_8INCLUDE_HOLY_SITE',				'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
VALUES	('REQ_MUKURO_8INCLUDE_HOLY_SITE',				'DistrictType',	'DISTRICT_SOTS_COAST_HOLY_SITE'),
		('REQ_MUKURO_8INCLUDE_HOLY_SITE',				'MinRange',		0),
		('REQ_MUKURO_8INCLUDE_HOLY_SITE',				'MaxRange',		8);