return {
    "wortox_nabbag",--强抢袋



    "pumpkincarver1",--南瓜勺
    "pumpkincarver2",--南瓜刀
    "pumpkincarver3",--南瓜锯

    "battlesong_container",--战斗号子罐
	"beargerfur_sack",--极地熊獾桶
    "antlionhat",--刮地皮头盔
    --钟表人工具
    "pocketwatch_portal",
    "pocketwatch_recall",
    "pocketwatch_heal",
    "pocketwatch_parts",
    -- "pocketwatch_revive_reviver",
    "pocketwatch_revive",
    "pocketwatch_dismantler",
    "pocketwatch_warp",
    --航海工具
    "dock_woodposts_item",--码头桩
    "boat_magnet_beacon",--自动航行灯塔
    "oar_monkey",--战桨
    
    "boat_bumper_yotd_kit",--獠牙保险杠套装
    "boat_bumper_crabking_kit",--帝王蟹保险杠套装
    "boat_bumper_shell_kit",--贝壳保险杠套装
    "boat_bumper_kelp_kit",--海带保险杠套装
    "ocean_trawler_kit",--海洋拖网捕鱼器套装
    "boat_rotator_kit",--转向舵套装
    "boat_magnet_kit",--自动航行套装
    "boat_cannon_kit",--大炮套装
    "boat_grass_item",--草筏套装
    
    "oar",
    "oar_driftwood",
    "malbatross_beak",
    "mast_item",
    "mast_malbatross_item",
    "mastupgrade_lamp_item",
    "mastupgrade_lightningrod_item",
    "anchor_item",
    "steeringwheel_item",
    "boatpatch",
    "boatpatch_kelp",--海带补丁
    "boat_ancient_item",--古董船套装
    "boat_item",
    --采集工具
    "shadow_battleaxe",--暗影槌

    "shovel_lunarplant",--亮茄铲子
    "pickaxe_lunarplant",--亮茄粉碎者
    "axe",
    "goldenaxe",
    "moonglassaxe",
    "lucy",
    "pickaxe",
    "goldenpickaxe",
    "multitool_axe_pickaxe",
    "shovel",
    "goldenshovel",
    --农业工具
    "farm_plow_item",
    "farm_hoe",
    "golden_farm_hoe",
    "premiumwateringcan",
    "wateringcan",
    "compost",
    "fertilizer",
    "soil_amender",
    "soil_amender_fermented",
    "plantregistryhat",
    "nutrientsgoggleshat",
    --装修工具
    "hammer",
    "pitchfork",
    "goldenpitchfork",--黄金干草叉
    --刮毛工具
    "razor",
    --书写工具
    "featherpencil",
    --训牛工具
    "brush",
    "saddle_shadow",--梦魇鞍具
    "saddle_basic",
    "saddle_race",
    "saddle_war",
    "saddlehorn",
    "saddle_wathgrithr",--战斗鞍具
    --烹饪工具
    "portablecookpot_item",
    "portableblender_item",
    "portablespicer_item",
    --施肥工具
    "fertilizer",
    --照明工具
    "torch",
    "lighter",
    "pumpkin_lantern",
    "redlantern",
    "yots_redlantern",--红灯笼
    -- "yots_worm_lantern",--红灯笼
    "lantern",
    "miniboatlantern",
    "minerhat",
    "molehat",
    --降温灭火工具
    "waterballoon",
    "featherfan",
    "perdfan",
    --降温避雨工具
    "minifan",
    "grass_umbrella",
    "umbrella",
    --地图工具
    "compass",
    "miniflare",
    "megaflare",--敌对信号弹
    --打包工具
    "giftwrap",
    "bundlewrap",
    --缝纫工具
    "sewing_kit",
    "sewing_tape",
    --过夜工具
    "bedroll_straw",
    "bedroll_furry",
    "portabletent_item",
    "portablefirepit_item",--便携营火
    --保温工具
    "heatrock",
    --狩猎工具
    "birdtrap",
    "trap",
    "bugnet",
    "thulecitebugnet",--铥矿捕虫网
    "fishingnet",
    "fishingrod",
    "oceanfishingrod",
    "chum",
    "tacklecontainer",
    "supertacklecontainer",
    "elixir_container",--野餐盒
    "slingshotmodkit",--弹弓野外作业包

    "oceanfishinglure_spinner_red",
    "oceanfishinglure_spinner_green",
    "oceanfishinglure_spinner_blue",
    "oceanfishinglure_spoon_red",
    "oceanfishinglure_spoon_green",
    "oceanfishinglure_spoon_blue",
    "oceanfishinglure_hermit_drowsy",
    "oceanfishinglure_hermit_heavy",
    "oceanfishinglure_hermit_rain",
    "oceanfishinglure_hermit_snow",
    "oceanfishingbobber_ball",
    "oceanfishingbobber_oval",
    "oceanfishingbobber_crow",
    "oceanfishingbobber_robin",
    "oceanfishingbobber_robin_winter",
    "oceanfishingbobber_canary",
    "oceanfishingbobber_goose",
    "oceanfishingbobber_malbatross",
    --称重工具
    "pocket_scale"
}
