local seg_time = 30
local total_day_time = seg_time*16

-- 骨灰罐保鲜倍率
TUNING.SISTURN_PRESERVER_MULT_1 = 0.75
TUNING.SISTURN_PRESERVER_MULT_2 = 0.6

-- 骨灰罐生产哀悼荣耀速率
TUNING.SISTURN_GHOSTFLOWER_PRODUCE_TIME_1 = total_day_time
TUNING.SISTURN_GHOSTFLOWER_PRODUCE_TIME_2 = total_day_time * 0.75

-- 阿比盖尔一级血量增益
TUNING.ABIGAIL_HEALTH_LEVEL1_SKILLTREE_1 = 200
TUNING.ABIGAIL_HEALTH_LEVEL2_SKILLTREE_1 = 350
TUNING.ABIGAIL_HEALTH_LEVEL3_SKILLTREE_1 = 650

-- 阿比盖尔二级血量增益
TUNING.ABIGAIL_HEALTH_LEVEL1_SKILLTREE_2 = 250
TUNING.ABIGAIL_HEALTH_LEVEL2_SKILLTREE_2 = 450
TUNING.ABIGAIL_HEALTH_LEVEL3_SKILLTREE_2 = 800

-- 易伤时间增加
TUNING.ABIGAIL_VEX_DURATION_SKILLTREE = 4

-- 易伤的两个倍率
TUNING.ABIGAIL_VEX_DAMAGE_MOD_SKILLTREE = 1.2
TUNING.ABIGAIL_VEX_GHOSTLYFRIEND_DAMAGE_MOD_SKILLTREE = 1.5

-- 阿比盖尔防御
TUNING.ABIGAIL_DAMAGE_ABSORPTION = 0.60

-- 灵体草药的持续时间
TUNING.ELIXIR_DURATION = total_day_time * 1.5

-- 亡者补药回复速率改为5点
TUNING.ELIXIR_SLOWREGEN_ENHANCE = 5

-- 灵魂万灵药的回复速率改为40点
TUNING.ELIXIR_FASTREGEN_ENHANCE = 40

--
TUNING.ELIXIR_SHIELD_ENHANCE = 1.25

--
TUNING.ELIXIR_RETALIATION_ENHANCE = 30

--
TUNING.ELIXIR_ATTACK_ENHANCE = 45

TUNING.ELIXIR_SPEED_ENHANCE = 9.5

TUNING.WENDY_MORE_ELIXIR_RATE_1 = 0.25

TUNING.WENDY_MORE_ELIXIR_RATE_2 = 0.40

TUNING.WENDY_PICK_HERB_RATE_1 = 0.05

TUNING.WENDY_PICK_HERB_RATE_2 = 0.1

TUNING.WENDY_ALLEGIANCE_LUNAR_RESIST = 0.9
TUNING.WENDY_ALLEGIANCE_VS_SHADOW_BONUS = 1.1

TUNING.WENDY_ALLEGIANCE_SHADOW_RESIST = 0.9
TUNING.WENDY_ALLEGIANCE_VS_LUNAR_BONUS = 1.1

-- 姐妹故事书的小号
TUNING.SISTERS_STORIES_SPELL_COST = {
    SWEET_MEMORY = 0.05,
    CASTLING = 0.10,
    SAME_HEART = 0.05,
    SMALL_CONTRADICTION = 0.2,
    MOON_ESSENCE = 0.1,
    SHADOW_PRESENT = 0.5
}

TUNING.SISTERS_STORIES_SANITY_COST = {
    SWEET_MEMORY = -10,
    CASTLING = -25,
    SAME_HEART = -15,
    SMALL_CONTRADICTION = -25,
    MOON_ESSENCE = -25,
    SHADOW_PRESENT = -50
}
