local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.WX = "WX-type Automaton"
STRINGS.RECIPE_DESC.WX = "A brand-new automaton."
STRINGS.NAMES.WXDIVININGROD = "Voxola PR-76"
STRINGS.RECIPE_DESC.WXDIVININGROD = "Portable signal trasmitter."
STRINGS.NAMES.WXDIVININGRODBASE = "PR-76 Plateform"
STRINGS.RECIPE_DESC.WXDIVININGRODBASE = "Socket for a trasmitter."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WX = "The crown jewel of industry."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WX = "It's a pity that your shell hardly catches fire."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WX = "Tiny robot wants to be Wolfgang's friend."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WX = "Do you feel hollow inside?"
STRINGS.CHARACTERS.WX78.DESCRIBE.WX = "ONE OF MY DEAREST SIBLINGS"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WX = "It looks like the prototype of WX-78."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WX = "You can use an axe. Great."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WX = "Its design is quite different from my clockwork attendants."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WX = "Follow close behind, soldier!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WX = "You look more non-organic than yesterday!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.WX = "Best workmate ya can ever count on!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.WX = "It can help to take care of my little garden."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WX = "Bad robot likes to hurt my friends!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.WX = "Looks like a new Pioneer joined the troop!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WX = "Ooo, a soul-free walking tin!"
STRINGS.CHARACTERS.WURT.DESCRIBE.WX = "Not watertight enough to hold water, florp."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WX = "Great! A mass produced automaton can save my time!"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WILLOW.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WENDY.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WENDY.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WX78.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WX78.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WOODIE.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WEBBER.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WINONA.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WINONA.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WARLY.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WARLY.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WALTER.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WALTER.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WORTOX.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WURT.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WURT.DESCRIBE.DIVININGROD
STRINGS.CHARACTERS.WANDA.DESCRIBE.WXDIVININGROD = STRINGS.CHARACTERS.WANDA.DESCRIBE.DIVININGROD

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WILLOW.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WENDY.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WENDY.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WX78.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WX78.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WOODIE.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WEBBER.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WINONA.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WINONA.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WARLY.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WARLY.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WALTER.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WALTER.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WORTOX.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WURT.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WURT.DESCRIBE.DIVININGRODBASE
STRINGS.CHARACTERS.WANDA.DESCRIBE.WXDIVININGRODBASE = STRINGS.CHARACTERS.WANDA.DESCRIBE.DIVININGRODBASE

STRINGS.CHARACTERS.WX = STRINGS.CHARACTERS.WX78
STRINGS.CHARACTERS.WX.DESCRIBE = STRINGS.CHARACTERS.WX78.DESCRIBE

STRINGS.CHARACTERS.WX.ANNOUNCE_BUILT = "LOCAL UNIT ONLINE"
STRINGS.CHARACTERS.WX.ANNOUNCE_NO_OCUVUGIL = "WARNING: NO OCUVIGIL DETECTED"
STRINGS.CHARACTERS.WX.ANNOUNCE_NO_CONTAINER = "WARNING: MORE CONTAINERS REQUIRED"
STRINGS.CHARACTERS.WX.ANNOUNCE_DAMAGED = "WARNING: SHELL INTEGRITY COMPROMISED"
STRINGS.CHARACTERS.WX.ANNOUNCE_REPAIRED = "SHELL INTEGRITY RESTORED"
STRINGS.CHARACTERS.WX.ANNOUNCE_RESURRECTION_START = "VM MIGRATION SEQUENCE INITIATED"
STRINGS.CHARACTERS.WX.ANNOUNCE_RESURRECTION_FINISH = "VM MIGRATION SEQUENCE COMPLETE"
STRINGS.CHARACTERS.WX.ANNOUNCE_WASHED_ASHORE = "WARNING: SHIP DESTROYED"
STRINGS.CHARACTERS.WX.ANNOUNCE_COOK =
{
    NO_RECIPE = "ERROR: UNDEFINED RECIPE",
    LOOP = "RECIPES ITERATED, LOOP REFINING MODE ENABLED",
    ONETIME = "RECIPES ITERATED, ONETIME REFINEMENT SEQUENCE COMPLETE",
    MANUAL = "CONFIG FILE NOT FOUND, MANUAL REFINING MODE ENABLED",
}
STRINGS.CHARACTERS.WX.ANNOUNCE_TRANSPORTATION_START = "NAVIGATION SYSTEM ONLINE"
STRINGS.CHARACTERS.WX.ANNOUNCE_TRANSPORTATION_JUMP_START = "HYPER SPACE JUMP IMMINENTS"
STRINGS.CHARACTERS.WX.ANNOUNCE_TRANSPORTATION_JUMP_FINISH = "LANDING SUCCESS"
STRINGS.CHARACTERS.WX.ANNOUNCE_TRANSPORTATION_NODESTINATION = "WARNING: NO AVAILABLE DESTINATION"
STRINGS.CHARACTERS.WX.ANNOUNCE_EQUIP =
{
    ACCEPT = "NEW HARDWARE INSTALLED",
    REFUSE = "IMCOMPATIBLE HARDWARE",
}
STRINGS.CHARACTERS.WX.ANNOUNCE_BACKPACK =
{
    TOGGLE_ON = "EXTERNAL STORAGE ACCESS GRANTED",
    TOGGLE_OFF = "EXTERNAL STORAGE ACCESS DENIED",
}