name = "Indestructible Eye Mask"
description = "\"Eye Mask\" and \"Shield Of Terror\" will not break when their durability reaches zero."
author = "π"
version = "1.0"
forumthread = ""
icon_atlas = "modicon.xml"
icon = "modicon.tex"
dst_compatible = true
client_only_mod = false
all_clients_require_mod = true
api_version = 10
configuration_options = {}