local STRINGS = GLOBAL.STRINGS
STRINGS.CHARACTERS.WONDERWHY.DESCRIBE.WONDERWHY = {
    GENERIC = "One more.",
    ATTACKER = "There aren't many left of us.",
    MURDERER = "There might not be many left.",
    REVIVER = "New beginning to mortal decay.",
    GHOST = "And there were none.",
    FIRESTARTER = "There should be none of you.",}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WONDERWHY = {
	GENERIC = "Hello %s!",
	ATTACKER = "%s, knew you were trouble.",
	MURDERER = "%s's ancient rage has awoken!",
	REVIVER = "%s's maybe not so bad!",
	GHOST = "Saw that coming soon enough.",
    FIRESTARTER = "%s seeks warmth, in an odd way...",}
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WONDERWHY = {
	GENERIC = "Scary monstaz, super creeps!",
	ATTACKER = "Don't fight %s! Wolfgang will break you!",
	MURDERER = "Wolfgang didn't expect that...",
	REVIVER = "Ancient friend unkilled Wolfgang!",
	GHOST = "Lol??? Noob.",
    FIRESTARTER = "I'll throw you under the water!",}
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WONDERWHY = {
	GENERIC = "Share with me your knowledge, %s...",
	ATTACKER = "Was it you, or not you...?",
	MURDERER = "Ancient seek their ways.",
	REVIVER = "Thank you for the blessing of life %s.",
	GHOST = "Seek better form, and rebirth.",
    FIRESTARTER = "Is it... because of me?",}
STRINGS.CHARACTERS.WX78.DESCRIBE.WONDERWHY = {
	GENERIC = "HOW DO YOU MOVE",
	ATTACKER = "DESTRUCTION PROTOCOL ACTIVATED",
	MURDERER = "GO SLAY FOUL BEAST",
	REVIVER = "FIXER UPPER",
	GHOST = "WEREN'T YOU DEAD FROM THE BEGINNING?",
    FIRESTARTER = "MASS DESTRUCTOR",}
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WONDERWHY = {
	GENERIC = "Eww what a creep, %s? Was it?",
	ATTACKER = "Noupe.",
	MURDERER = "It's beginning to look a lot like...",
	REVIVER = "That was cool I guess.",
	GHOST = "Do we have to help you?",
    FIRESTARTER = "I fight fire with fire you know?",}
STRINGS.CHARACTERS.WENDY.DESCRIBE.WONDERWHY = {
	GENERIC = "Hollow friend, shall thy lead me to the darkness?",
	ATTACKER = "Dance death incarnate.",
	MURDERER = "How i long for a death...",
	REVIVER = "Leave me be, leave me where i belong.",
	GHOST = "Abigail's new friend?",
    FIRESTARTER = "Ruin this world, with me in it.",}
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WONDERWHY = {
	GENERIC = "Damn what kind of bear is this, eh?",
	ATTACKER = "Ya wanna go?!",
	MURDERER = "They want to go outside!",
	REVIVER = "Thanks paps. Blegh...",
	GHOST = "That's what yall good at!",
    FIRESTARTER = "I'll chop you into even more pieces!",}
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WONDERWHY = {
	GENERIC = "Genderless and enigmatic.",
	ATTACKER = "Hostile and full of rage.",
	MURDERER = "I should have known you were no good after all...",
	REVIVER = "I'm sorry I ever doubted you dear.",
	GHOST = "What happened to your face darling?",
    FIRESTARTER = "What is their motive?",}
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WONDERWHY = {
	GENERIC = "Spoopy friend, hello %s!",
	ATTACKER = "No fair! You could hurt someone, that's no fun!",
	MURDERER = "We are sad now!",
	REVIVER = "You are different than you seem.",
	GHOST = "Don't be a dummy next time.",
    FIRESTARTER = "%s! Right in front of our salad!?",}
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WONDERWHY = {
	GENERIC = "You must be my nemesis!",
	ATTACKER = "Oh? Ready for our finale?",
	MURDERER = "Won't forgive you fiend!",
	REVIVER = "Why? Your heart is ruled by darkness!?",
	GHOST = "I'll have your soul too!",
    FIRESTARTER = "Who let the demon into the hayloft!?",}
STRINGS.CHARACTERS.WINONA.DESCRIBE.WONDERWHY = {
	GENERIC = "%s? Ok. Bye now.",
	ATTACKER = "What's wrong with you?!",
	MURDERER = "You better have an excuse. For murder...",
	REVIVER = "With good paws, good work will be made!",
	GHOST = "When you're out there could you please look for my sis?",
    FIRESTARTER = "Am I a joke to you?",}
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WONDERWHY = {
	GENERIC = "Kiss me.. wait you don't have lips....",
	ATTACKER = "A lil prankster, like myself.",
	MURDERER = "Hyuyuyu and frick you.",
	REVIVER = "Teach me your ways!",
	GHOST = "You are just a little fractured, but wholesome.",
    FIRESTARTER = "Eat your matchsticks while you can!",}
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WONDERWHY = {
	GENERIC = "Plant food",
	ATTACKER = "Don't step on grass",
	MURDERER = "Bad friend",
	REVIVER = "Me bloom again",
	GHOST = "Serves you right",
    FIRESTARTER = "Plants will eat you someday",}
STRINGS.CHARACTERS.WARLY.DESCRIBE.WONDERWHY = {
	GENERIC = "Eat something you look thin.",
	ATTACKER = "Bone soup?",
	MURDERER = "Bone soup it is.",
	REVIVER = "Acquired taste!",
	GHOST = "Again?",
    FIRESTARTER = "Go back to the kitchen.",}
STRINGS.CHARACTERS.WURT.DESCRIBE.WONDERWHY = {
	GENERIC = "Glorby florby flurb burb!",
	ATTACKER = "Warrior!",
	MURDERER = "Monster!",
	REVIVER = "Spooky stuff!",
	GHOST = "Don't tire yourself?",
    FIRESTARTER = "Stop it!",}
STRINGS.CHARACTERS.WALTER.DESCRIBE.WONDERWHY = {
	GENERIC = "Woby don't touch %s!",
	ATTACKER = "Woby! Get his bones!",
	MURDERER = "Blood thirsty monsters do not scare me!",
	REVIVER = "Hmph, ok then...",
	GHOST = "%s in their natural habitat...",
    FIRESTARTER = "You'll die from fire someday you know?",}
STRINGS.CHARACTERS.WANDA.DESCRIBE.WONDERWHY = {
	GENERIC = "Last time you weren't so nice.",
	ATTACKER = "Keep your claws at bay, will you?",
	MURDERER = "Botheration! To hell with you!",
	REVIVER = "I'm no longer late.",
	GHOST = "Reminder to never be you.",
    FIRESTARTER = "Perish, time will catch up to you eventually!",}