local STRINGS = GLOBAL.STRINGS
STRINGS.CHARACTERS.WONDERWHY.DESCRIBE.WONDERWHY = {
    GENERIC = "One more of us... Me?",
    ATTACKER = "There aren't many of our kind left.",
    MURDERER = "Settle down, your anger is unjust.",
    REVIVER = "%s is kind hearted despite their state.",
    GHOST = "We're supposed to rebuild ourselves, not crumble further %s.",
    FIRESTARTER = "%s has developed impulsive arsonistic manners.",}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WONDERWHY = {
	GENERIC = "Hello %s!",
	ATTACKER = "%s, knew you were trouble.",
	MURDERER = "%s's ancient rage has awoken!",
	REVIVER = "%s's maybe not so bad!",
	GHOST = "Saw that coming soon enough.",
    FIRESTARTER = "%s seeks warmth, in an odd way...",}
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WONDERWHY = {
	GENERIC = "Scary horn man is maybe friend with other horn man!",
	ATTACKER = "Scary horn man is mean!",
	MURDERER = "Wolfgang will crush horn man!",
	REVIVER = "Wolfgang sorry for calling you scary, %s.",
	GHOST = "Wolfgang will fix Ancient friend!",
    FIRESTARTER = "%s is need big fires?",}
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WONDERWHY = {
	GENERIC = "Hmph, I didn't think your kind would return, Mx. %s.",
	ATTACKER = "Mx. %s seems full of ill intents.",
	MURDERER = "%s's Ancient anger has awakened itself!",
	REVIVER = "%s is acting quite selfless for their state, respectable.",
	GHOST = "I've been there %s, I'll aid you.",
    FIRESTARTER = "I didn't think your kin had fire rituals, %s.",}
STRINGS.CHARACTERS.WX78.DESCRIBE.WONDERWHY = {
	GENERIC = "DETECTING... MINERALS... NO WAIT. %S IS JUST OLD ROCKS HAHA",
	ATTACKER = "THE PEBBLES ARE AGGRESSIVE",
	MURDERER = "I'LL GRIND YOU AWAY",
	REVIVER = "GOOD PERFORMANCE, FOR A PILE OF STONES",
	GHOST = "YOU'RE A RATHER WEAK MINION",
    FIRESTARTER = "I APPRECIATE YOUR EVILNESS BUT YOU MUST STOP",}
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WONDERWHY = {
	GENERIC = "Hi, %s, how's it rocking?",
	ATTACKER = "Hey! I've left you alone, do the same!",
	MURDERER = "Too bad rocks don't burn well.",
	REVIVER = "%s is quite nice, for old rubbles!",
	GHOST = "You must feel lighter now %s.",
    FIRESTARTER = "Aww, you should've told me we were setting things on fire!",}
STRINGS.CHARACTERS.WENDY.DESCRIBE.WONDERWHY = {
	GENERIC = "I feel a hole in your heart too, %s.",
	ATTACKER = "%s seeks to end some lives.",
	MURDERER = "It is time you stop hunting, %s!",
	REVIVER = "%s seems to wish to postone our departure.",
	GHOST = "Abigail finds you adorable.",
    FIRESTARTER = "%s has quite a destructive behavior.",}
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WONDERWHY = {
	GENERIC = "You and that imp are related, %s?",
	ATTACKER = "You seem pretty angry %s!",
	MURDERER = "I'll chop you down!",
	REVIVER = "%s is an alright sort!",
	GHOST = "%s! I'll get you a heart!",
    FIRESTARTER = "The fire goes in the pit, %s.",}
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WONDERWHY = {
	GENERIC = "Ah, greetings dear %s! How fares your research?",
	ATTACKER = "I will not tolerate that behavior from anyone, %s!",
	MURDERER = "Your murderous intents end there %s!",
	REVIVER = "%s grasps that altruism is power.",
	GHOST = "Oh dear, %s needs a bit of aid.",
    FIRESTARTER = "Behave, %s.",}
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WONDERWHY = {
	GENERIC = "Hello, %s! Wanna play?",
	ATTACKER = "We don't like this game.",
	MURDERER = "We will get you for that, %s!",
	REVIVER = "Thanks for the help, %s!",
	GHOST = "Would a dinosaur band-aid make it better?",
    FIRESTARTER = "Ms. Wickerbottom gets mad when we play with fire, %s.",}
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WONDERWHY = {
	GENERIC = "Mímir's blessing upon you, %s!",
	ATTACKER = "You wish to test my worth %s?",
	MURDERER = "I shall return you to your grave!",
	REVIVER = "%s has a great sense of honor and altruism!",
	GHOST = "Fear not! Valhalla is not ready for you!",
    FIRESTARTER = "Do not toy with Hel's flames %s!",}
STRINGS.CHARACTERS.WINONA.DESCRIBE.WONDERWHY = {
	GENERIC = "How's it going in the new world, %s?",
	ATTACKER = "You sure seem upset at us.",
	MURDERER = "No killer's getting away with me here!",
	REVIVER = "%s has great values!",
	GHOST = "Some elbow grease and you'll be all fine, %s!",
    FIRESTARTER = "Let's not start fires, shall we %s?",}
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WONDERWHY = {
	GENERIC = "Ooohoo, I quite like your ways %s!",
	ATTACKER = "That's not a nice prank, %s!",
	MURDERER = "Your tools disappearing were none of my doing, no sir, no sir!",
	REVIVER = "A caprine to the other must have kinship in order!",
	GHOST = "Quite a good look on you! Hyuyu!",
    FIRESTARTER = "You've been playing pranks without me!",}
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WONDERWHY = {
	GENERIC = "Oh, %s has funny head thing",
	ATTACKER = "Why %s mean?",
	MURDERER = "No! Don't hurt friends!",
	REVIVER = "%s made floaty friend whole again",
	GHOST = "Oh, %s is floaty friend now",
    FIRESTARTER = "Please don't!",}
STRINGS.CHARACTERS.WARLY.DESCRIBE.WONDERWHY = {
	GENERIC = "Tell me, %s did your kind have any ancestral dishes?",
	ATTACKER = "Mon cher! Don't act as such!",
	MURDERER = "Je suis désolé, I must put an end to you %s!",
	REVIVER = "%s is very kind hearted, merci!",
	GHOST = "We should give a hand to %s, bien sûr!",
    FIRESTARTER = "Fires stay in the oven, mon ami.",}
STRINGS.CHARACTERS.WURT.DESCRIBE.WONDERWHY = {
	GENERIC = "Hello rocky!",
	ATTACKER = "Why mad?",
	MURDERER = "Meanie!",
	REVIVER = "Knew we be friends!",
	GHOST = "Me will get you heart!",
    FIRESTARTER = "Stop it!",}
STRINGS.CHARACTERS.WALTER.DESCRIBE.WONDERWHY = {
	GENERIC = "Hello %s! How's it crumbling?",
	ATTACKER = "%s doesn't have their funny bone anymore, haha!",
	MURDERER = "You don't scare me %s!",
	REVIVER = "That's really nice of you %s!",
	GHOST = "Oh no, we'll get you right back in your... skeleton!",
    FIRESTARTER = "You can make a real fire with a bit of grass, let me show you!",}
STRINGS.CHARACTERS.WANDA.DESCRIBE.WONDERWHY = {
	GENERIC = "Oh yes, you %s! I had something to tell you...",
	ATTACKER = "Keep your claws at bay, will you?",
	MURDERER = "Botheration! I'll send you back to your time!",
	REVIVER = "Thank you for the turn back in time %s.",
	GHOST = "I'll get you back on your feet %s.",
    FIRESTARTER = "A fire is sadly the few things that are too fast.",}
