local STRINGS = GLOBAL.STRINGS
STRINGS.CHARACTERS.WONDERWHY.DESCRIBE.WONDERWHY = {
    GENERIC = "Uno más de nosotros... ¿Yo?",
    ATTACKER = "No quedan muchos de nuestro tipo.",
    MURDERER = "Cálmate, tu ira es injusta.",
    REVIVER = "%s es de buen corazón a pesar de su estado.",
    GHOST = "Se supone que debemos reconstruirnos, no desmoronarnos más %s.",
    FIRESTARTER = "%s ha desarrollado costumbres incendiarias impulsivas.",}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Hola, %s!",
	ATTACKER = "%s, sabía que eras un problema.",
	MURDERER = "¡La antigua ira de %s ha despertado!",
	REVIVER = "¡Quizás %s no sea tan malo!",
	GHOST = "Lo vi venir muy pronto.",
    FIRESTARTER = "%s busca calidez, de una manera extraña...",}
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Aterrador hombre con cuernos tal vez sea amigo del otro hombre con cuernos!",
	ATTACKER = "¡Aterrador hombre con cuernos es malo!",
	MURDERER = "¡Wolfgang aplastará al hombre con cuernos!",
	REVIVER = "Wolfgang lamenta haberte llamado aterrador, %s.",
	GHOST = "¡Wolfgang arreglará al amigo ancestral!",
    FIRESTARTER = "¿%s necesita grandes fuegos?",}
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WONDERWHY = {
	GENERIC = "Hm, no pensé que los de tu clase regresarían, Dx. %s.",
	ATTACKER = "Dx. %s parece lleno de malas intenciones.",
	MURDERER = "¡El enojo ancestral de %s se despertó así mismo!",
	REVIVER = "%s está actuando bastante desinteresado para su estado, respetable.",
	GHOST = "He estado allí %s, te ayudaré.",
    FIRESTARTER = "No pensé que tus parientes tuvieran rituales de fuego, %s.",}
STRINGS.CHARACTERS.WX78.DESCRIBE.WONDERWHY = {
	GENERIC = "DETECTANDO... MINERALES... NO ESPERA. %S ES SÓLO ROCAS VIEJAS JA, JA",
	ATTACKER = "LOS GUIJARRITOS SON AGRESIVAS",
	MURDERER = "TE MOLERÉ HACIA AFUERA",
	REVIVER = "BUEN DESEMPEÑO, PARA UNA PILA DE PIEDRAS",
	GHOST = "ERES UN MINION BASTANTE DÉBIL",
    FIRESTARTER = "APRECIO TU MALDAD PERO DEBES PARAR",}
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WONDERWHY = {
	GENERIC = "Hola, %s, ¿cómo le va a la roca?",
	ATTACKER = "¡Ey! ¡Te he dejado en paz, haz lo mismo!",
	MURDERER = "Lástima que las rocas no arden bien.",
	REVIVER = "¡%s es bastante bueno, para escombros viejos!",
	GHOST = "Debes sentirte más ligero ahora %s.",
    FIRESTARTER = "¡Ohh, debiste haberme dicho que estábamos prendiendo cosas en fuego!",}
STRINGS.CHARACTERS.WENDY.DESCRIBE.WONDERWHY = {
	GENERIC = "Siento un agujero en tu corazón también, %s.",
	ATTACKER = "%s busca acabar con algunas vidas.",
	MURDERER = "¡Es hora de que dejes de cazar, %s!",
	REVIVER = "%s parece querer posponer nuestra partida.",
	GHOST = "Abigail te encuentra adorable.",
    FIRESTARTER = "%s tiene un comportamiento bastante destructivo.",}
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WONDERWHY = {
	GENERIC = "¿Tú y ese diablillo están relacionados, %s?",
	ATTACKER = "¡Pareces bastante enojado %s!",
	MURDERER = "¡Te talaré!",
	REVIVER = "¡%s es un buen tipo!",
	GHOST = "¡%s! ¡Te conseguiré un corazón!",
    FIRESTARTER = "El fuego va al pozo, %s.",}
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Ah, saludos querido %s! ¿Cómo va su investigación?",
	ATTACKER = "¡No toleraré ese comportamiento de nadie, %s!",
	MURDERER = "¡Tus intenciones asesinas terminan aquí %s!",
	REVIVER = "%s comprende que el altruismo es poder.",
	GHOST = "Oh querido, %s necesita un poco de ayuda.",
    FIRESTARTER = "Compórtate, %s.",}
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Hola, %s! ¿Quieres jugar?",
	ATTACKER = "A nosotros no nos gusta este juego.",
	MURDERER = "¡Te atraparemos por eso, %s!",
	REVIVER = "¡Gracias por la ayuda, %s!",
	GHOST = "¿Una curita de dinosaurio lo mejoraría?",
    FIRESTARTER = "La Sra. Wickerbottom se enoja cuando jugamos con fuego, %s.",}
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WONDERWHY = {
	GENERIC = "¡La bendición de Mímir para ti, %s!",
	ATTACKER = "¿Quieres probar mi valor, %s?",
	MURDERER = "¡Te devolveré a tu tumba!",
	REVIVER = "¡%s tiene un gran sentido del honor y altruismo!",
	GHOST = "¡No temáis! ¡Valhalla no está lista para ti!",
    FIRESTARTER = "¡No juegues con las llamas de Hel, %s!",}
STRINGS.CHARACTERS.WINONA.DESCRIBE.WONDERWHY = {
	GENERIC = "¿Cómo te va en el nuevo mundo, %s?",
	ATTACKER = "Pareces molesto con nosotros.",
	MURDERER = "¡Ningún asesino se saldrá conmigo aquí!",
	REVIVER = "¡%s tiene excelentes valores!",
	GHOST = "¡Un poco de grasa del codo y todo estará bien, %s!",
    FIRESTARTER = "No provoquemos incendios, ¿de acuerdo %s?",}
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Oooh, me gustan bastante tus maneras, %s!",
	ATTACKER = "¡Esa no es una broma agradable, %s!",
	MURDERER = "La desaparición de tus herramientas no fue nada de mi hacer, ¡no señor, no señor!",
	REVIVER = "¡Un caprino para el otro debe tener parentesco en poder!",
	GHOST = "¡Qué buena pinta tienes! ¡Ji, ji!",
    FIRESTARTER = "¡Has estado gastando bromas sin mí!",}
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WONDERWHY = {
	GENERIC = "Oh, %s tiene una cosa para la cabeza graciosa",
	ATTACKER = "¿Por qué %s malo?",
	MURDERER = "¡No! ¡No lastimes a amigos!",
	REVIVER = "%s hizo amigo flotante entero de nuevo",
	GHOST = "Oh, %s es amigo flotante ahora",
    FIRESTARTER = "¡Por favor no hagas!",}
STRINGS.CHARACTERS.WARLY.DESCRIBE.WONDERWHY = {
	GENERIC = "Dime, %s ¿los de tu especie tenían algún plato ancestral?",
	ATTACKER = "¡Mon cher! ¡No actúes como tal!",
	MURDERER = "¡Je suis désolé, Debo ponerte un final, %s!",
	REVIVER = "¡%s es muy bondadoso, merci!",
	GHOST = "¡Deberíamos echarle una mano a %s, bien sûr!",
    FIRESTARTER = "Los fuegos se quedan en el horno, mon ami.",}
STRINGS.CHARACTERS.WURT.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Hola roquita!",
	ATTACKER = "¿Por qué enojado?",
	MURDERER = "¡Malito!",
	REVIVER = "¡Sabía que éramos amigos!",
	GHOST = "¡Te conseguiré corazón!",
    FIRESTARTER = "¡Basta!",}
STRINGS.CHARACTERS.WALTER.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Hola %s! ¿Cómo le desmorona?",
	ATTACKER = "%s ya no tiene su hueso de la risa, ¡ja, ja!",
	MURDERER = "¡No me asustas, %s!",
	REVIVER = "¡Eso es muy amable de tu parte, %s!",
	GHOST = "Oh no, te devolveremos a tu... ¡esqueleto!",
    FIRESTARTER = "Puedes hacer un fuego real con un poco de hierba, ¡déjame enseñarte!",}
STRINGS.CHARACTERS.WANDA.DESCRIBE.WONDERWHY = {
	GENERIC = "¡Oh, sí, tú, %s! Tenía algo que decirte...",
	ATTACKER = "Mantén tus garras a raya, ¿quieres?",
	MURDERER = "¡Fastidio! ¡Te enviaré de regreso a tu tiempo!",
	REVIVER = "Gracias por el regreso en el tiempo %s.",
	GHOST = "Te ayudaré a volver sobre tus pies, %s.",
    FIRESTARTER = "Un incendio lamentablemente es una de las pocas cosas que suceden demasiado rápido.",}
