local SEE_WORK_DIST = TUNING.WXAUTOMATION.SEE_WORK_DIST
local KEEP_WORKING_DIST = SEE_WORK_DIST + 6

local WXFreight = Class(function(self, inst)
    self.inst = inst
end)

--[[
ACTIONS.RAISE_SAIL
ACTIONS.LOWER_SAIL
ACTIONS.LOWER_SAIL_BOOST
ACTIONS.LOWER_SAIL_FAIL
ACTIONS.RAISE_ANCHOR
ACTIONS.LOWER_ANCHOR
ACTIONS.STEER_BOAT
ACTIONS.SET_HEADING
ACTIONS.STOP_STEERING_BOAT
]]

function WXFreight:SailTo()
end

return WXFreight