---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Erii.
--- DateTime: 2022/11/10 21:07
---

---获取局部变量
function _G.OceanGetLocalFn(fn, fname, nofn)
    if not (fn and fname) then
        return
    end
    local index = 1
    repeat
        local name, val = debug.getupvalue(fn, index)
        if name and name == fname then
            if val and (nofn or type(val) == "function") then
                return val
            end
        end
        index = index + 1
    until not name
end

function _G.OceanGetListenFn(inst, event, source)
    if type(inst) == "table" then
        if inst.event_listening and inst.event_listening[event] then
            local listenings = inst.event_listening[event]
            for _, v in pairs(listenings) do
                if v and type(v) == "table" then
                    for _, v1 in pairs(v) do
                        if type(v1) == "function" then
                            local info = debug.getinfo(v1)
                            if info.source and info.source:match(source) then
                                return v1
                            end
                        end
                    end
                end
            end
        end
    end
end