---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Erii.
--- DateTime: 2022/10/18 6:56
---

local function crabking_spawner_server(player)
    if STRINGS.MUSHA_CRABKING_SPAWNER_L == nil then
        local crabking_spawner = TheSim:FindFirstEntityWithTag("crabking_spawner")
        if crabking_spawner then
            STRINGS.MUSHA_CRABKING_SPAWNER_L = { crabking_spawner.Transform:GetWorldPosition() }
            local loc = json.encode(STRINGS.MUSHA_CRABKING_SPAWNER_L)
        end
    end
    if STRINGS.MUSHA_CRABKING_SPAWNER_L then
        local loc = json.encode(STRINGS.MUSHA_CRABKING_SPAWNER_L)
        SendModRPCToClient(GetClientModRPC("musha_crabking_spawner", "crabking_spawner"), player, loc)
    end
end
AddModRPCHandler("musha_crabking_spawner", "crabking_spawner", crabking_spawner_server)

local function crabking_spawner_client(l)
    STRINGS.MUSHA_CRABKING_SPAWNER_L = json.decode(l)
end
AddClientModRPCHandler("musha_crabking_spawner", "crabking_spawner", crabking_spawner_client)