---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Erii.
--- DateTime: 2022/11/10 8:46
---

local function undertile(self)

    local _underneath_tiles

    local function InitializeDataGrid(src, data)
        if _underneath_tiles == nil then
            _underneath_tiles = OceanGetLocalFn(self.GetTileUnderneath, "_underneath_tiles", true)
        end
    end
    self.inst:ListenForEvent("worldmapsetsize", InitializeDataGrid, TheWorld)

    function self:GetTileUnderneath2(x, y)
        return _underneath_tiles:GetDataAtPoint2(x, y)
    end

    function self:SetTileUnderneath2(x, y, tile)
        _underneath_tiles:SetDataAtPoint2(x, y, tile)
    end

    --local old_OnSave = self.OnSave
    function self:OnSave()
        local data = {}

        data.underneath_tiles = _underneath_tiles:Save()
        data.underneath2_tiles = _underneath_tiles.ocean_grid

        return ZipAndEncodeSaveData(data)
    end

    --local old_OnLoad = self.OnLoad
    function self:OnLoad(data)
        data = DecodeAndUnzipSaveData(data)
        if data == nil then
            return
        end

        local tile_id_conversion_map = TheWorld.tile_id_conversion_map

        _underneath_tiles:Load(data.underneath_tiles)
        _underneath_tiles.ocean_grid = data.underneath2_tiles or {}
        for k, v in pairs(_underneath_tiles.grid) do
            _underneath_tiles.grid[k] = tile_id_conversion_map[v] or v
        end
    end

end
AddComponentPostInit("undertile", undertile)