---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Erii.
--- DateTime: 2022/11/14 13:28
---

local function datagrid(self)

    self.ocean_grid = {}

    function self:GetDataAtPoint2(x, y)
        return self:GetDataAtIndex2(self:GetIndex(x, y))
    end

    function self:SetDataAtPoint2(x, y, data)
        return self:SetDataAtIndex2(self:GetIndex(x, y), data)
    end

    function self:GetDataAtIndex2(index)
        --print("=====GetDataAtIndex2 ", self.ocean_grid[index])
        return self.ocean_grid[index]
    end

    function self:SetDataAtIndex2(index, data)
        --print("=====SetDataAtIndex2 ", data)
        self.ocean_grid[index] = data
    end

    --local old_Save = self.Save
    --function self:Save()
    --    local grids = {}
    --    local grid = old_Save and old_Save(self) or {}
    --    grids.grid = grid
    --    grids.ocean_grid = self.ocean_grid
    --    return grids
    --end

    --local old_Load = self.Load
    --function self:Load(grids)
    --    if old_Load then
    --        old_Load(self, grids.grid or {})
    --    end
    --    self.ocean_grid = grids.ocean_grid or {}
    --end
end
AddGlobalClassPostConstruct("datagrid", "DataGrid", datagrid)