TUNING.APIARY =
{
    FETALS_CONVERSION_COUNTER = TUNING.TOTAL_DAY_TIME * 1.5,
    HONEY_CONVERSION_COUNTER = TUNING.TOTAL_DAY_TIME * 4.5,
    MAX_FETALS_CONVERSION_PERDAY = GetModConfigData("extraoutput") or 6,
    MAX_HONEY_CONVERSION_PERDAY = GetModConfigData("jellyoutput") or 1,
    CONVERT_INTERVAL = 5,
    FEED_INTERVAL = 15,
    HARVEST_INTERVAL = TUNING.TOTAL_DAY_TIME,
}

TUNING.PERISH_BEEBOX_MULT = TUNING.PERISH_SALTBOX_MULT