local GLOBAL = GLOBAL or _G
local TUNING = GLOBAL.TUNING or {}

local Brightness = GetModConfigData("Brightness")
local MODULE_USES = GetModConfigData("MODULE_USES")
local SCANNER_SCANPERIOD = GetModConfigData("SCANNER_SCANPERIOD")
local TASERDAMAGE = GetModConfigData("TASERDAMAGE")
local CHARGE_REGENTIME = GetModConfigData("CHARGE_REGENTIME")
local MINACCEPTABLEMOISTURE = GetModConfigData("MINACCEPTABLEMOISTURE")
local ICE = GetModConfigData("ICE")
local COLDRATE = GetModConfigData("COLDRATE")
local BEE_TICKPERIOD = GetModConfigData("BEE_TICKPERIOD")
local MOVESPEED = GetModConfigData("MOVESPEED")
local MUSIC = GetModConfigData("MUSIC")
local SLOWPERCENT = GetModConfigData("SLOWPERCENT")
local MAXSANITY_DAPPERNESS = GetModConfigData("MAXSANITY_DAPPERNESS")
local MAXHEALTH_BOOST = GetModConfigData("MAXHEALTH_BOOST")
--local day_time = TUNING.day_time

--照明模块范围
TUNING.WX78_LIGHT_BASERADIUS = Brightness
TUNING.WX78_LIGHT_EXTRARADIUS = math.max(Brightness - 4, 1.5)

--模块使用次数
TUNING.WX78_MODULE_USES = MODULE_USES

--电力回复时间间隔
TUNING.WX78_CHARGE_REGENTIME = CHARGE_REGENTIME

--扫描器
TUNING.WX78_SCANNER_SCANPERIOD = SCANNER_SCANPERIOD
TUNING.WX78_SCANNER_MODULETARGETSCANTIME = SCANNER_SCANPERIOD
TUNING.WX78_SCANNER_MODULETARGETSCANTIME_EPIC = SCANNER_SCANPERIOD * 2

--光电伤害
TUNING.WX78_TASERDAMAGE = TASERDAMAGE

--防水能力
TUNING.WX78_MINACCEPTABLEMOISTURE = MINACCEPTABLEMOISTURE

--制冷电路清除潮湿度制冰
if ICE == 1 then
	TUNING.WX78_COLD_ICEMOISTURE = math.min(MINACCEPTABLEMOISTURE - 1, 14)
	TUNING.WX78_COLD_ICECOUNT = 1
end

--制冷电路保鲜
TUNING.WX78_PERISH_COLDRATE = COLDRATE

--豆增压电路提高回血速率
TUNING.WX78_BEE_TICKPERIOD = BEE_TICKPERIOD

--超级处理器电路、豆增压电路回san速率
if MAXSANITY_DAPPERNESS ~= 0 then
	TUNING.WX78_MAXSANITY_DAPPERNESS = MAXSANITY_DAPPERNESS
end

--3个超级加速电路无衰减叠加
if MOVESPEED == 1 then
	TUNING.WX78_MOVESPEED_CHIPBOOSTS = {0.00, 0.25, 0.50, 0.75}
end

-- 合唱盒电路
TUNING.WX78_MUSIC_DAPPERNESS = 100/(300*MUSIC*2)
TUNING.WX78_MUSIC_SANITYAURA = 100/(300*MUSIC)

--胃增益饥饿消耗
TUNING.WX78_MAXHUNGER_SLOWPERCENT = SLOWPERCENT

--强化电路和超级强化电路
TUNING.WX78_MAXHEALTH_BOOST = MAXHEALTH_BOOST